### ISSUE TITLE
crashes on 1.15.2 upon clicking floor with prefab in hand

### ISSUE THREAD

**Issue by Seegras** [Brian-Wuest/MC-Prefab#127]
Could of course be some mod-interaction, or a forge version issue. 

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 28/02/20 12:45
Description: Rendering screen

java.lang.NoClassDefFoundError: javafx/util/Pair
	at com.wuest.prefab.Structures.Gui.GuiStartHouseChooser.getAdjustedXYValue(GuiStartHouseChooser.java:75) ~[?:1.5.0.1] {re:classloading}
	at com.wuest.prefab.Structures.Gui.GuiStartHouseChooser.render(GuiStartHouseChooser.java:83) ~[?:1.5.0.1] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:359) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2-forge-31.1.12.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.12.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
Caused by: java.lang.ClassNotFoundException: javafx.util.Pair
	at java.lang.ClassLoader.findClass(ClassLoader.java:524) ~[?:1.8.0_242] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:101) ~[modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242] {}
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.wuest.prefab.Structures.Gui.GuiStartHouseChooser.getAdjustedXYValue(GuiStartHouseChooser.java:75)
	at com.wuest.prefab.Structures.Gui.GuiStartHouseChooser.render(GuiStartHouseChooser.java:83)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:359)

-- Screen render details --
Details:
	Screen name: com.wuest.prefab.Structures.Gui.GuiStartHouseChooser
	Mouse location: Scaled: (232, 131). Absolute: (927.000000, 524.000000)
	Screen size: Scaled: (464, 262). Absolute: (1854, 1048). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Seegras1'/273, l='MpServer', x=-964.39, y=64.00, z=170.21]]
	Chunk stats: Client Chunk Cache: 1369, 961
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: -7451148600238514520
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-192,67,-64), Chunk: (at 0,4,0 in -12,-4; contains blocks -192,0,-64 to -177,255,-49), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 651875 game time, 787967 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:442)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1764)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:568)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 5.5.6
	Java Version: 1.8.0_242, Debian
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Debian
	Memory: 2585856224 bytes (2466 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 8
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.12.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.12.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.0-milestone.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.12.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.12.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.12.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.12
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotori_scala@2.13.1-build-6
	Mod List: 
		followingvillagers-1.15.2-1.4.0.jar Following Villagers {followingvillagers@1.15.2-1.4.0 DONE}
		AdditionalEnchantedMiner-1.15.2-15.2.1.jar QuarryPlus {quarryplus@15.2.1 DONE}
		chanceglobe-1.15.2-v1.3.2.jar Chance Globe {chanceglobe@v1.3.2 DONE}
		prefab-1.5.0.1.jar Prefab {prefab@1.5.0.1 DONE}
		EditSign-1.15.2-2.0.0+7.jar Edit Sign {edit_sign@2.0.0+7 DONE}
		ProjectE-1.15.2-PE1.0.2B.jar ProjectE {projecte@1.0.2B DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		IndustrialAgriculture[Core]-1.15.2-1.5.4.jar Industrial Agriculture {industrialagriculture@1.15.2-1.5.4 DONE}
		music_player-1.15.2-2.0.12.63.jar Music Player {musicplayer@2.0.12.63 DONE}
		rsgauges-1.15.2-1.2.1.jar Gauges and Switches {rsgauges@1.2.1 DONE}
		Island_Generator[1.15.2]-1.0.0.jar Island Generator {islandgenerator@1.0.0 DONE}
		IronJetpacks-1.15.2-3.0.0.jar Iron Jetpacks {ironjetpacks@3.0.0 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 DONE}
		BetterSprinting-1.15.2-v3.1.0.jar Better Sprinting {bettersprinting@3.1.0 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		dankstorage-2.5.jar Dank Storage {dankstorage@2.5 DONE}
		sneakthroughberries-1.15.2-20w06a-1.0.1.jar Sneak Through Berries {sneakthroughberries@1.15.2-20w06a-1.0.1 DONE}
		Powah-1.15.2-1.1.2.jar Powah {powah@1.1.2 DONE}
		rangedpumps-0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 DONE}
		WitherSkeletonTweaks-1.15.1-4.0.0.jar Wither Skeleton Tweaks {wstweaks@4.0.0 DONE}
		u_team_core-1.15.2-2.10.6.155.jar U Team Core {uteamcore@2.10.6.155 DONE}
		Apotheosis-1.15.2-3.0.4.jar Apotheosis {apotheosis@3.0.4 DONE}
		LightingWand-1.15.2-1.4.2.jar Lighting Wand {lightingwand@1.4.2 DONE}
		Morpheus-1.15.2-4.2.47.jar Morpheus {morpheus@version DONE}
		advancedtools-1.15.2-1.0.1.jar Advanced Tools {advancedtools@1.15.2-1.0.1 DONE}
		MekanismGenerators-1.15.2-9.9.10.402.jar Mekanism: Generators {mekanismgenerators@9.9.10 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WaterStrainer-1.15.1-8.0.0.jar Water Strainer {waterstrainer@1.15.1-8.0.0 DONE}
		speedyhoppers-1.15.2-2.jar Speedy Hoppers {speedyhoppers@1.15.2-2 DONE}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 DONE}
		shulkerbox-1.9.1.jar Advanced Shulkerboxes {shulkerbox@1.9.1 DONE}
		ExpOreMod-1.15.2-1.1.jar Exp Ore Block {exp_ore@1.1 DONE}
		TOOLKIT-1.15.2-1.6.4.jar Tool Kit {toolkit@1.15.2-1.6.4 DONE}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		quartz-chests-1.1.0.5.jar Quartz Chests {quartzchests@1.1.0.5 DONE}
		mcw-bridges-1.0.3-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.3 DONE}
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 DONE}
		industrial-foregoing-1.15.2-2.2.1-f27c515.jar Industrial Foregoing {industrialforegoing@2.2.1 DONE}
		angermanagement-1.15.2-1.0.0.jar Anger Management Mod {angermanagement@1.15.2-1.0.0 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		entangled-1.1.4-mc1.15.2.jar Entangled {entangled@1.1.2 DONE}
		smartdispensers-1.0.jar Smart Dispensers {smartdispensers@1 DONE}
		BiomesOPlenty-1.15.2-10.0.0.338-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.338 DONE}
		valkyrielib-1.15.2-3.0.2.1.jar ValkyrieLib {valkyrielib@1.15.2-3.0.2.1 DONE}
		simplechunkloaders-1.15.2-1.0.2.0.jar Simple Chunk Loaders {simplechunkloaders@NONE DONE}
		valhelsia_structures-1.15.1-0.0.1.jar Valhelsia Structures {valhelsia_structures@1.15.1-0.0.1 DONE}
		Lollipop-1.15.2-1.0.4.jar Lollipop {lollipop@1.0.4 DONE}
		ironfurnaces-1.15.2-2.0.0.jar Iron Furnaces {ironfurnaces@2.0.0 DONE}
		wtbw_lib-1.15.2-1.0.8.jar WTBW Library {wtbw_lib@1.0.8 DONE}
		SilentGear-1.15.2-1.5.2+77.jar Silent Gear {silentgear@1.5.2+77 DONE}
		tgcropesmod-1.15.2-1.1.1.jar Ropes Mod {tgcropesmod@1.15.2-1.1.1 DONE}
		horsemodifiers-1.15.2-1.2.jar Horse Modifiers {horsemodifiers@1.2 DONE}
		simplybackpacks-1.15.2-1.3.0.jar Simply Backpacks {simplybackpacks@1.15.2-1.3.0 DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 DONE}
		curios-FORGE-1.15.2-2.0-beta2.jar Curios API {curios@FORGE-1.15.2-2.0-beta2 DONE}
		Clay WorldGen-1.1.0-1.15.1.jar Clay WorldGen {clayworldgen@version DONE}
		RingOfBlink-1.15.2-1.1.14.jar Ring of Blink {ring_of_blink@1.1.14 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		RingOfMiner-1.15.2-1.1.14.jar Ring of Miner {ring_of_miner@1.1.14 DONE}
		wtbw_tools-1.15.2-1.0.6.jar WTBW Tools {wtbw_tools@1.0.6 DONE}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE DONE}
		tanknull-1.7.jar Tank Null {tanknull@1.7 DONE}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 DONE}
		f2l-0.3.1.jar Flesh 2 Leather {f2l@0.3.1 DONE}
		additionalevents-1.0a.jar Additional Events {additionalevents@1.0a DONE}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha DONE}
		libnonymous-1.15.2-1.1.1.5.jar Libnonymous {libnonymous@1.1.1.5 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		Gobber2-1.15.2-2.2.45.jar Gobber 2 {gobber2@2.2.45 DONE}
		tombstone-4.2.2-1.15.2.jar Corail Tombstone {tombstone@4.2.2 DONE}
		RingOfEnderchest-1.15.2-1.1.14.jar Ring of Enderchest {ring_of_enderchest@1.1.14 DONE}
		PowderPower-1.15.2-3.1.34.jar Powder Power {powder_power@3.1.34 DONE}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c DONE}
		MekanismTools-1.15.2-9.9.10.402.jar Mekanism: Tools {mekanismtools@9.9.10 DONE}
		ChunkNoGoByeBye-1.15.2-1.2.0.jar ChunkNoGoByeBye {chunknogobyebye@1.15.2-1.2.0 DONE}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 DONE}
		betterwithminecolonies-1.15.2-1.13.14.jar Better With Minecolonies {betterwithminecolonies@1.15.2-1.13.14 DONE}
		CobbleForDays-1.1.1.jar Cobble For Days {cobblefordays@1.1.1 DONE}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 DONE}
		Disenchanting_(forge)_1.15.2-1.2.0.jar Disenchanting {disenchanting@1.2.0 DONE}
		CleanView-1.15.2-v1.jar CleanView {cleanview@1.15.2-v1 DONE}
		blockactions-0.1-1.15.2.jar Block Actions {blockactions@0.0.1-1.15.2 DONE}
		Treasure-Bags-1.15.2-1.2.0+20.jar Treasure Bags {treasurebags@1.2.0+20 DONE}
		Cyclic-1.15.2-0.1.10.jar Cyclic {cyclic@1.15.2-0.1.10 DONE}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		Cucumber-1.15.2-3.0.1.jar Cucumber Library {cucumber@3.0.1 DONE}
		mobgrinder-1.3.jar Mob Grinder {mobgrinder@1.3 DONE}
		mining-helmet-1.15.2-1.0.6.jar Mining Helmet {mining_helmet@1.0.6 DONE}
		craftingstation-3.0.5.jar Crafting Station {craftingstation@3.0.5 DONE}
		snad-1.8.3.3a-1.15.2.jar Snad {snad@1.8.3.3a DONE}
		Overloaded-1.15.2-0.0.84.jar Overloaded {overloaded@1.15.2-0.0.82 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		metalbarrels-2.1.jar Metal Barrels {metalbarrels@2.1 DONE}
		longfallboots-1.4.0b.jar Long Fall Boots {longfallboots@1.4.0b DONE}
		Mekanism-1.15.2-9.9.10.402.jar Mekanism {mekanism@9.9.10 DONE}
		AutoDropper-1.15.1-6.0.0.jar Auto Dropper {autodropper@1.15.1-6.0.0 DONE}
		RingOfRepair-1.15.2-1.1.14.jar Ring of Repair {ring_of_repair@1.1.14 DONE}
		LightOverlay-4.2.jar Light Overlay Forge {lightoverlay-forge@4.2 DONE}
		comforts-FORGE-1.15.2-2.0.jar Comforts {comforts@FORGE-1.15.2-2.0 DONE}
		NaturesCompass-1.15.2-1.8.4.jar Nature's Compass {naturescompass@1.15.2-1.8.4 DONE}
		good-nights-sleep-1.15.2-1.0.2.jar Good Night's Sleep {goodnightsleep@1.0.2 DONE}
		EnderBags-1.15.1-5.0.0.jar Ender Bags {ender_bags@5.0.0 DONE}
		SimpleStorageNetwork-1.15.2-0.2.4.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 DONE}
		SereneSeasons-1.15.2-3.0.0.65-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.65 DONE}
		gardentools-1.15.2-1.0.0.jar Garden Tools {gardentools@1.15.2-1.0.0 DONE}
		engineerstools-1.15.2-1.0.6-b2.jar Engineer's Tools {engineerstools@1.0.6-b2 DONE}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 DONE}
		RingOfTeleport-1.15.2-1.1.15.jar Ring of Teleport {ring_of_teleport@1.1.15 DONE}
		BonsaiTrees-2.1.2.6.jar Bonsai Trees 2 {bonsaitrees2@2.1.2.6 DONE}
		mcjtylib-1.15-4.0.1-alpha.jar McJtyLib {mcjtylib@1.15-4.0.1-alpha DONE}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha DONE}
		rftoolsstorage-1.15-1.0.1-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.1-alpha DONE}
		ClickMachine-1.15.2-3.0.1.jar Click Machine {clickmachine@3.0.1 DONE}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 DONE}
		environmentalcreepers-forge-1.15.2-1.6.1.jar Environmental Creepers {environmentalcreepers@1.6.1 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		PackingTape-1.15.2-0.9.5.jar Packing Tape {packingtape@0.9.5 DONE}
		infinityworkswithallarrows-1.0.jar Infinity works with all arrows {infinityworkswithallarrows@1.0 DONE}
		endercompass-2.0.jar Ender Compass {endercompass@2.0 DONE}
		CraftTweaker-1.15.2-6.0.0.6.jar CraftTweaker {crafttweaker@6.0.0.6 DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		campfiretorches-1.15.2-1.0.2.jar Campfire Torches {campfiretorches@1.15.2-1.0.2 DONE}
		forge-1.15.2-31.1.12-universal.jar Forge {forge@31.1.12 DONE}
		PassthroughSigns-1.15.1-2.3.2.jar Passthrough Signs {passthroughsigns@1.15.1-2.3.2 DONE}
		wtbw_core-1.15.2-1.0.9.jar WTBW Core {wtbw_core@1.0.9 DONE}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 DONE}
		coffeebreak-1.5.jar Softcat's Coffee Break {coffeebreak@1.5 DONE}
		forge-1.15.2-31.1.12-client.jar Minecraft {minecraft@1.15.2 DONE}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha DONE}
		clockout-1.15.2-1.0.0.jar Clockout {clockout@1.15.2-1.0.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.15.2-1.14.0.jar Tool Belt {toolbelt@1.14.0 DONE}
		titanium-1.15.2-2.3.6.jar Titanium {titanium@2.3.6 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		wtbw_machines-1.15.2-1.0.7.jar WTBW Machines {wtbw_machines@1.0.7 DONE}
		overworld_mirror-1.15.2-1.3.0.12.jar Overworld Mirror {overworldmirror@1.3.0.12 DONE}
		RingOfGrowth-1.15.2-1.1.15.jar Ring of Growth {ring_of_growth@1.1.15 DONE}
		theplopper-1.15.1-v1.3.jar The Plopper {theplopper@v1.3 DONE}
		forbidden_arcanus-1.15.2-1.1.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 DONE}
		packedup-1.0.3-mc1.15.2.jar PackedUp {packedup@1.0 DONE}
		LargeFluidTank-15.2.3.jar FluidTank {fluidtank@15.2.3 DONE}
		BerryBushes-1.1.1.jar Berry Bushes {berrybushes@1.1.1 DONE}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha DONE}
		dimdungeons-1.03-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.14.4-1.03 DONE}
		flux-4.8.0.jar Flux {flux@4.8.0 DONE}
		fl-3.0.7.jar Flux Library {fl@3.0.7 DONE}
		Xaeros_Minimap_20.3.1.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.3.1 DONE}
		ShulkerTooltip-1.9.2.jar Shulker Tooltip {shulkertooltip@1.9.2 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		torcherino-10.0.1.jar Torcherino {torcherino@10.0.1 DONE}
		StorageDrawers-1.15.2-7.0.1.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		backpacked-1.4.1-1.15.2.jar Backpacked {backpacked@1.4.1 DONE}
		vanillahammers-1.15.1-1.0.jar Vanilla Hammers {vanillahammers@1.15.1-1.0 DONE}
		tubesreloaded-1.15.2-1.2.0.jar Tubes Reloaded {tubesreloaded@1.15.2-1.2.0 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		engineersdecor-1.15.2-1.0.19-b3.jar Engineer's Decor {engineersdecor@1.0.19-b3 DONE}
		moredragoneggs-1.0.jar More Dragon Eggs {moredragoneggs@1.0 DONE}
		RingOfAttraction-1.15.2-1.1.18.jar Ring of Attraction {ring_of_attraction@1.1.18 DONE}
		Aquaculture-1.15.2-2.0.8.jar Aquaculture 2 {aquaculture@1.15.2-2.0.8 DONE}
		SilentGems-1.15.2-3.5.1+84.jar Silent's Gems 3 {silentgems@3.5.1+84 DONE}
		XL-Food-Mod-1.15.2-2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 DONE}
		waterworks-1.15.2-2.1.0.jar Waterworks {waterworks@1.15.2-2.1.0 DONE}
		Industrial Agriculture[Mekanism]-1.15.2-1.5.2.jar Industrial Agriculture Plugin-Mekanism {iapmekanism@1.15.2-1.5.2 DONE}
		CHAS v1.3 for 1.15.jar Craftable Horse Armour {craftablehorsearmour@1.3 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		Ma-Essentials-1.15.2-3.0.0.jar Ma Essentials {ma-essentials@1.15.2-3.0.0 DONE}
		extremeSoundMuffler-beta-1.15.2-1.0.jar Extreme Sound Muffler {extremesoundmuffler@beta-1.15.2-1.0 DONE}
		SolarGeneration-1.15.2-1.2.0.jar Solar Generation {solargeneration@1.2.0 DONE}
		parachutemod-1.15.2-2.3.2-471.jar Parachute Mod NG {parachutemod@1.15.2-2.3.2-471 DONE}
		SuperTools-1.1_1.15.2.jar Super Tools {supertools@1.1 DONE}
		Omega Craft 4.0.9 - 1.15.2.jar Omega Craft {omegacraft@1.0 DONE}
		lootbagmod-1.15.1-1.4.jar Loot Bag Mod {lootbagmod@1.15.1-1.4 DONE}
		draw_bridge-1.15.2-1.4.3.18.jar Draw Bridge {drawbridge@1.4.3.18 DONE}
		xptome-1.15.1-v1.1.4.jar XP Tome {xpbook@v1.1.4 DONE}
		bigbuckets-1.1.0.jar BigBuckets {bigbuckets@1.1.0 DONE}
	Kiwi Modules: 
		kiwi:contributors
		snowrealmagic:snowrealmagic
	Launched Version: 1.15.2-forge-31.1.12
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.59, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by Brian-Wuest** [comment]
1. Please use something like pastebin or another similar site when posting large logs
2. You are using OpenJDK which I don't support. I don't support this due to Minecraft being made with Oracle JDK. Until/unless Minecraft makes the switch I will not support OpenJDK. 
    1. Just make a quick oracle account and download the JDK.

Closing issue

**Comment by Seegras** [comment]
This is not an openjdk issue.

**Comment by Brian-Wuest** [comment]
java.lang.NoClassDefFoundError: javafx/util/Pair
at com.wuest.prefab.Structures.Gui.GuiStartHouseChooser.getAdjustedXYValue(GuiStartHouseChooser.jav

This error is telling me that you are using OpenJDK and not Oracles JDK.

**Comment by Seegras** [comment]
This is on Debian, and I won't install some JDK from some spurious source that doesn't even offer Debian packages. For one mod out of 180. Which worked in 1.14.4 with the same JDK.

**Comment by Brian-Wuest** [comment]
Understandable, if you would like to see this fixed please create a pull request and I can merge it in. I am currently working on the update to 1.14 for Repurpose which is no small effort and also working on some updates for From The Depths so I won't get to this for a while.

I will re-open this so someone (if you don't want too) can do the pull request if I don't get to it by then.

**Comment by Seegras** [comment]
Just for informational purposes. https://gist.github.com/androidfred/bc64da9e6a355b984d37439ed63ae16b -- turns out I have openjfx, but only for JDK 11.

**Comment by Brian-Wuest** [comment]
This has been fixed with 1.4.0.12 and 1.5.0.2.

Note: The 1.5.0.2 version is currently going through the CurseForge approval process and will be available for download once it is approved.

Closing issue.
