### ISSUE TITLE
[1.14.4] Sidedness issue when run on a server NoSuchMethodError: net.minecraft.entity.player.PlayerInventory.func_184429_b(Lnet/minecraft/item/ItemStack;)I

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#101]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: forge-1.14.4-28.0.45
    1. Mod Version: prefab-1.4.0.0
1. What type of issue is this? Choose one of the following:
    1. **Bug**

Every mod updating to 1.14.4 has had sidedness issues, they changed how it works in 1.14.

Crash log-
https://gist.github.com/ProsperCraft/5c6dabd293b024fb0c3590505fc8dc1e

Modpack-
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

**Comment by Brian-Wuest** [comment]
I was able to figure out what was wrong and address the defect. This will be fixed with 1.4.0.1 which is being uploaded/reviewed by curseforge right now.

Closing this issue.
